#sdk: "/Users/MOHUS/rhodes"
sdkversion: 3.3.3
name: LongListTest
version: 1.0
vendor: tautech
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator9.1
  BundleIdentifier: com.tautech.longlisttest
  BundleURLScheme: longlisttest
  codesignidentity: iPhone Developer
  entitlements: ""
  emulatortarget: iphone
  production:
    ipa_itunesartwork_image: "./production/iTunesArtwork.png"  

wp:
  productid: 'ede53d30-67b9-012f-fcba-3c075408aa51'
symbian:
  uid: '0xeb98fa92'

android:
  version: 2.1

extensions: ["json", "nlist"]
